zone: blin.dev

external-dns:
  # TODO: confirm default don't work
  image:
    registry: k8s.gcr.io
    repository: external-dns/external-dns
    tag: v0.7.6

  provider: cloudflare
  cloudflare:
    secretName: cloudflare-api-key
    proxied: false