zone: blin.dev

external-dns:
  # TODO: confirm default don't work
  image:
    registry: k8s.gcr.io
    repository: external-dns/external-dns
    tag: v0.7.6

  logLevel: debug

  domainFilters:
  - blin.dev
  sources:
  - service

  provider: cloudflare
  cloudflare:
    email: louis@blin.dev
    secretName: cloudflare-api-key
    proxied: false