apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgCDfKNLV36oI3ql3hV3UUGwj4kET7eb+55J1qHNvMiAlbHrXuucCQzRaMNd+bqjKOYDEwzIA/kVj2LG0EV5hzwiU3FCD9EBWG8njV583QJqsPfAixzG7Blf8oMHDnn78o55tB6b2NPXHSA9Qv8M9kGUZeWvzbrBsy1dGMsyjhMWsiNye5CO+KhMRb9mpOmYmG8ZSJYiUo6Dlavmq23MEQxImT89R08qR7XAm7O/6kwnA5+r7wnkErWlwAIYnkyL7rB7kU9iv1xCrjkKuNg7Nr6zEXBTGBQkG/n43uN+bcuyt6d6AN6HI4R8/ypS/qYKaEcGoOQklVtTdn84JzBh2UiyrSuR1NSRepx6gpwo8+hRXVSIpkwJ5RN9nX5UJfq6g8zBUKlSqC3igYHE3aYj4MtTCKQKPc96yTqxMJW2MSdV3yZcPkwsB1Pxr/D0cgo7Yh2EZsBlV0sRYrXrWeqBqWq78Y5+gTKjfAFBFyCOj1jPjU5AGoklyU5bbtBphJwvP/7FbZE4eD0HRr4v1/AldGzRQ4YiV8ihdi8vvBYgzzv/kcmhTyScyKNUV8GoB6j8z6/WW+3OhpyZ0okxODC7BRknmnmqIgEEtys5F2NJRFwmHNLyHN2Z5ctIKZ9FxU/qKhQ+JDFCnmlN4wtbHX2JIkAL+/qYRqvcmHYzSke3avwHv4KuRLZ79DqVyMp63Af0TdpX4yrQof7k5sAXDUIC9x4REdLGvDc8uaUW1l/mazQtnZKDDBnpIbMl
  template:
    metadata:
      name: argocd-secret
      namespace: argocd

