apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    server.secretkey: AgAgPkZibGb8dJ1NPzV96XWrLFnl8kivs3GRrvKYx+avh72p9aWUK6SV55OM9MLXyVlyAAtBtwwsxftVxXrvZTII8jpWGa9qp7oPvzpt9F2dIPqZCmgZHvtiQ+EFeK8PE5yLgSbcIFyohqBLUc/oVW/pNqcYHrPKO+NJyeWRcuBgJ4iPctRlfuo9BvNtjPz0pTjqUJHFDupwA5nZWWogRWISjARpu+CNnzWZPPjYxmcIiXHNjXpeuTAGn+Oihz4ZUP1poSDdVZ6W0gIVqRZU3Nta398ImmghPzkJGmmbPYdgSD9e/wcHzODggHv27rQCuWK+82NpWaTmy+u2nyGueUmXGy+QjDgtcx0mDsYGKRroQ2bNNQw5owW8TGQAAuC5Uab1FBw7jOGX7Fwz9/CH9y2PQxQsKiER3eSS+rSlaQgu5YtU0n0668bT2I0jHjEizG55qw7rDnvupaxsrPMvaXLDowqe2EPB3QuWZlL6aVZHHdE9vR+ZsdpMPZfApU0NG+N7AbU1Y3XlOyYeJUV/+HF7dnVshFvKPbzTAs/im7SycbRX141okewtQWr0+mmJHqOsRd+LxhZusTaWnBo7RLQneHiUoTncojGFmickA95CRLBKnuNe5jm5+4Ave8Avs/VjYmN4qJuHSbbtff4/qndDiWafQCeTo9im1ce5OR7Q9BNCg5ZEQIlvycH9upd8TloYjjwDXMAnvXu8mIyIPYshwWSgJs4AK1hEbbabOEfIrA16VH4Kxfcz
    webhook.github.secret: AgAZdZEUzQafppJ2LjU/OZTp4Yrd/Bvy2QidSWjBVwa6aLMWtuM9HXDnQBeqbDFOpqlkwRsNnJr6eCNjgJfEc7TSNGnCxOw/GwC4iv4PtOGx8+2BjDmLRjcXHTeggK3oeZUkmLZQs5j/+pJCDutIMl5tkDOPqJlXEK2e9aJjTLc2txkOa0Zj+Nu50H0ZFjuw/z1V+abl/9CFYzK0NatAeJeVp94HbqY6DlwE7F3tSWkWp5S8AlXhObBno1+qDvftl3RKwn6K0RjgHON0YxWqTvGEaBCqNHxIy7XTz4GgORxlva8cbLj2J/EBhb0dGyxn0zybabHfSgRQleWo3YAIkKNfvMMazazMQrbpW9wyuuEHOQipsFteSBWlBDvrs82NUkTN7e0W+5Ur+sS5fP8TcE2TWqOU0O5eE5g6NUTpWO8R3QsfWK4qT979Xl+HYx2epe0IUfuFt0krB3K4EuK2od/yqqn/OA8lEZVD7eRmRasVVYMO1J88g+rBHVBTim5RzosNWAX5eHS7hMUHzva8YCRMixe51b1i2C5kgfOr7TmmUtMG2f4b9bL0TyUWqkqEtH7N109zCmMh8wBLh66Vmexcry7YpRg/+gZ+MloMxWENj7PYT5Z1Ogl9kXd4aite/FxrsxxXzBjbDmTrxPyP7vEibZ+SIUBPB5FKwTo0k2nUOpcCNkr4O2o2ypLbE2+GjR5Jq4+dgvCK5Gp9XhpeCg97+mp3+nAHZ176hTaE/nnbxzHWNtwgN8Sd
  template:
    metadata:
      name: argocd-secret
      namespace: argocd

