kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-external-name
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd.blin.dev
spec:
  type: ExternalName
  externalName: blin.dev
