apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-creds
  namespace: dns
spec:
  encryptedData:
    cloudflare_api_token: AgBgiQPg/CpN0yVM8RUCwM0+4hgQ0hN82fFdCnsfHWeYlMmraQWEAu7d0n3TLv7j1JHatTrZZfKHtQ8W83NDCwp22DXBHIMe+xQ9UIem+rDwRvFJHJY+LvVX0YrLII8Ds3hcnBy7Wlacztv0HiHChPH7sn0n5Q/cQFNLdfxYlomCXxlYEo56OwqsU5FlDbVn1T6SKGEmEFh3L+UNow7JEBJpI9BIENDZYhGaSs62eSLKmc0yfV4p09pH+tgWC/U7wEd7u+QXh55s7ghB22kNWvlT4x1Yc5IMQPXFAJRDVN674lo+jFglqO9nbCyyxhkXwFETZiSnwIdt2dlS1zBf8sHmgi7oAUtkN9NCLLWNIQWFBgaRCm8WXkrDdnedB2hNIXUUT8jZKK7My9KdxVIruGeTk6FdUfw/Co8SObu5Rr57tdKUAPOPUG0q4bKiTJz7CmE26DBeLL8DteDkVYv3qvx17nXzLxmJHlXjtsiI1ELnfsGcni9SWQFNh6CzYSE2c7itRcyHc/y8P4rTQUm22V0KalanaiRSxaCuLwi3R14o5CwT2c5VrgeS4XXsq06DPhm22oHj47MPDHY/iAY3zhiwWOQdU3F5U0vA5sXQ/wXEABgsNm/gnaGe80+0SJeGPQVgIreB/S+w47Fy7lImGMMAERNoBVlZ0lfmxZi889xowvp3tboNCIcO4JYkeEVpKX0EYMx2EJZ24GLCZb1f1Sgb1sV9+jAFXcIoPO7GcyOaO5d5kpaPm9tW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-creds
      namespace: dns

