apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dns.fullname" . }}-ddns
  labels:
    {{- include "dns.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dns.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-ddns
        image: oznu/cloudflare-ddns:latest
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudflare-creds
              key: cloudflare_api_token
        - name: ZONE
          value: {{ .Values.zone }}
        - name: PROXIED
          value: "false"
