traefik:
  deployment:
    additionalContainers:
    - name: ddns
      image: oznu/cloudflare-ddns:latest
      env:
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cloudflare-creds
            key: cloudflare_api_token
      - name: CUSTOM_LOOKUP_CMD
        value: |
          sh -c 'curl -sH "Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)" --cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt https://$KUBERNETES_PORT_443_TCP_ADDR:443/api/v1/namespaces/traefik/services/ | jq -r ".items[].status.loadBalancer.ingress[].hostname" | xargs dig +short | sort | head -n1'
      - name: ZONE
        value: blin.dev
      - name: PROXIED
        value: "false"

  providers:
    kubernetesIngress:
      ingressClass: traefik-internal
      publishedService:
        enabled: true

  # service:
  #   type: NodePort
