apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-api-key
  namespace: datadog
spec:
  encryptedData:
    api-key: AgCD/MUrhawltCpaJU2sA/vgG2169yMrBbN3XcevsaTByoF5fKkyaulVJvDrK4P8RQOOmS9FV6kJuF/yS9sMmUkV0rLHjI1Ij02Fh3kI5LzsjOYkl5KVVRUV59dH5zNclLs2Mwc2Y2VdkXALFakMy1VnMR8Vl9fEwZbHiUxB45hNY+wruAsU5y/3/vLsLdZzalnY2e7VexDLkaGrfvcgd+/Z3FHStWIk55MK3z8/tlL8thXDe1LSEqFdQEuhw+7zFlYl3fE8x3W7HzAIUV1ozYia7t0kJLUDUsc7HR20rcnfQRD0T0EDcnJ/hz2DMU9L0TMgylUcEk3/jgO10eYFpCFglNvxddNnOcO2c06U5FAEQRL3tHKWfS8cvnBGNxqAobfE4iwPCaxHuWtHhPfOh9EhwlmHonTkmtpCHCwVT0baIJJZkRZmJXW3yuVRo12PqlaB+2VuH2b2dbu2n2pzYRtFjKAt4QNTI7mUpytpwkrROvpuTKD9whcbCC9mzDzSdwsC78qQOwI0t183KWTI+AletJyJo2pL/nxAzWC2Q8rqnVEDJFPaB7R4IdZ5+XSXSlNryErZVGk20xD9TPNh8FABLPS/1q+hT/JAEDMsQbn54LzITw53QRE+JJNJTeqzKjlo5RgvMOqyRTVJ41nVWv0E035+7gmNWcGv6Gkax55U+gRefG6WL/tMkVBJZ7biUEIcl9RDm4lv50u6V3RrUI7ZoFsayeMW0tFrSda2Z6qPJQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: datadog-api-key
      namespace: datadog

