argo-cd:
  configs:
    repositories:
      git-kubernetes-deployments:
        type: git
        url: https://github.com/louisblin/kubernetes-deployments

      helm-bitnami:
        name: bitnami
        type: helm
        url: https://charts.bitnami.com/bitnami
      helm-datadog:
        name: datadog
        type: helm
        url: https://helm.datadoghq.com
      helm-jetstack:
        name: jetstack
        type: helm
        url: https://charts.jetstack.io
      helm-sealed-secrets:
        name: sealed-secrets
        type: helm
        url: https://bitnami-labs.github.io/sealed-secrets
      helm-utkuozdemir:
        name: utkuozdemir
        type: helm
        url: https://utkuozdemir.org/helm-charts

    secret:
      createSecret: false

  server:
    config:
      url: https://argocd.blin.dev

    extraArgs:
    - --insecure

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      hosts:
      - argocd.blin.dev
      tls:
      - hosts:
        - argocd.blin.dev
        secretName: argocd-tls

  applicationSet:
    enabled: false

  dex:
    enabled: false

  notifications:
    enabled: false
