global:
  image:
    repository: docker.io/alinbalutoiu/argocd
    tag: linux-arm64-v2.0.2

argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - argocd.blin.dev
      tls:
      - hosts:
        - argocd.blin.dev
        secretName: argocd-tls

  dex:
    enabled: false