argo-cd:
  configs:
    secret:
      createSecret: false

  server:
    extraArgs:
    - --insecure

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        kubernetes.io/tls-acme: "true"
      hosts:
      - argocd.blin.dev
      tls:
      - hosts:
        - argocd.blin.dev
        secretName: argocd-tls

    config:
      url: https://argocd.blin.dev
      repositories: |
        - name: kubernetes-deployments
          type: git
          url: https://github.com/louisblin/kubernetes-deployments

        - name: bitnami
          type: helm
          url: https://charts.bitnami.com/bitnami
        - name: datadog
          type: helm
          url: https://helm.datadoghq.com
        - name: jetstack
          type: helm
          url: https://charts.jetstack.io
        - name: sealed-secrets
          type: helm
          url: https://bitnami-labs.github.io/sealed-secrets
        - name: utkuozdemir
          type: helm
          url: https://utkuozdemir.org/helm-charts

  applicationSet:
    enabled: false

  dex:
    enabled: false

  notifications:
    enabled: false
