apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-llb
spec:
  storageClassName: llb
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /run/media/root/LLB